# Generated by Django 5.0.7 on 2024-07-24 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('cleanText', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityId', models.CharField(max_length=255)),
                ('applicationId', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('receivedAt', models.DateTimeField()),
                ('messageId', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=50)),
                ('content', models.ManyToManyField(to='two_way_messages.content')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='two_way_messages.platform')),
            ],
        ),
    ]
